### ISSUE TITLE
Instructions don't work using webpack 2.2.0

### ISSUE THREAD

**Issue by goesbysteve** [peerigon/modernizr-loader#28]
Using config as on readme (an .modernizrrc file as json) and importing Modernizr I get an error indicating the loader is not a loader. The file path in the log seems to indicate it's finding the Modernizr package and not the loader at all.

```
/Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/loader-runner/lib/loadLoader.js:35
                        throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
                        ^

Error: Module '/Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/im-fabric/node_modules/modernizr/lib/cli.js' is not a loader (must have normal or pitch function)
    at loadLoader (/Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/loader-runner/lib/LoaderRunner.js:164:2)
    at runLoaders (/Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/webpack/lib/NormalModule.js:129:2)
    at NormalModule.build (/Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/webpack/lib/NormalModule.js:180:15)
    at Compilation.buildModule (/Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/webpack/lib/Compilation.js:127:10)
    at factoryCallback (/Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/webpack/lib/Compilation.js:304:11)
    at /Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/webpack/lib/NormalModuleFactory.js:242:4
    at /Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/webpack/lib/NormalModuleFactory.js:93:13
    at /Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/tapable/lib/Tapable.js:204:11
```

If I change loader config to modernizr-loader I get a different error -

```
[16:07:34] ./.modernizrrc
Module build failed: /Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/im-fabric/.modernizrrc:2
  "minify": true,
          ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.exec (/Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/webpack/lib/NormalModule.js:98:6)
    at Object.module.exports (/Users/steve.gibbings/WebstormProjects/wcp-core/wordpress/themes/node_modules/modernizr-loader/index.js:24:26)
 @ ./src/js/view-model/common-vm.js 10:0-34
 @ ./src/js/entry.js
 @ multi ./src/js/polyfills/polyfills.js ./src/js/entry

```

**Comment by goesbysteve** [comment]
Sorry my mistake I had a typo!

**Comment by MartinMa** [comment]
@stevegibbings Hi, what was your typo? I get the same error "Unexpected token". Just updated to webpack 2.

**Comment by goesbysteve** [comment]
I hadn't amended the test value to include the json extension as webpack 2 now includes a json loader. Even though I have a file .modernizrrc with no extension the rules need to include exactly as on this loaders readme. I had just amended what I had from webpack 1 without looking close enough. I believe webpack 2 was loading it as JavaScript not json which caused the json-loader to fail parsing.

**Comment by MartinMa** [comment]
Thanks for your quick answer. I renamed `.modernizrrc` to `.modernizrrc.json` and changed the value for test to `/\.modernizrrc(\.json)?$/`. It does work now.

**Comment by goesbysteve** [comment]
You're welcome. Glad I could point you in the right direction. We've had lots to refactor to move to webpack 2 even though we were following the betas. Good luck!

**Comment by rflmyk** [comment]
I just  changed the loader name "modernizr" to "modernizr-loader" and work for me ;)
```
			{
				test: /\.modernizrrc(\.json)?$/,
				loader: "modernizr-loader!json-loader"
			}
```
I'm used webpack **2.2.1**
