### ISSUE TITLE
Config from readme gives "path is not defined"

### ISSUE THREAD

**Issue by drewnoakes** [peerigon/modernizr-loader#31]
Specifically, this line:

```
$ gulp
webpack.config.js:31
            modernizr$: path.resolve(__dirname, ".modernizrrc")
                        ^

ReferenceError: path is not defined
    at Object.<anonymous> (webpack.config.js:31:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (gulpfile.js:63:23)
    at Module._compile (module.js:570:32)
```

Do I need to add an import/require? If so, perhaps this could be included in the readme as well.

**Comment by flootr** [comment]
If you want to use the [`path`](https://nodejs.org/api/path.html) module, you need to require it in the file you're using it.

```js
const path = require('path');

// ...
```

I'll update the README file as well.

Let me know, if that solves your problem.

**Comment by drewnoakes** [comment]
Thanks.
